scrim2/views/home.py
from flask import Blueprint, render_template, json, g, current_app, redirect, url_for, session
from datetime import datetime as dt
from scrim2.extensions import oid, db, lm
from scrim2.models import User
from sqlalchemy.orm.exc import NoResultFound
from flask.ext.login import login_user, logout_user, current_user
import requests, re


home_bp = Blueprint('home_bp', __name__)

@home_bp.route('/')
def index():
    if current_user.is_authenticated():
        return redirect(url_for('live_bp.live'))
    return render_template('/home/index.html')

@home_bp.route('/login')
@oid.loginhandler
def login():
    """Log in via Steam OpenID

    """

    if g.user is not None:
        return redirect(oid.get_next_url())
    else:
        return oid.try_login('http://steamcommunity.com/openid')

@oid.after_login
def after_login(resp):
    """
    """
    steam_id_regex = re.compile('steamcommunity.com/openid/id/(.*?)$')
    steam_id = steam_id_regex.search(resp.identity_url).group(1)

    try:
        g.user = User.query.filter_by(steam_id=steam_id).one()
        user_info = get_user_info(g.user.steam_id)
        login_user(g.user)
        return redirect(oid.get_next_url())
    except NoResultFound:
        print "CREATIN USER"
        g.user = User()
        steam_data             = get_user_info(steam_id)
        g.user.steam_id        = steam_id
        g.user.nickname        = steam_data['personaname']
        g.user.avatar_url      = steam_data['avatar']
        g.user.avatar_url_full = steam_data['avatarfull']
        g.user.join_date       = dt.utcnow()
        db.session.add(g.user)
        db.session.commit()
        login_user(g.user)
        return redirect(url_for('home_bp.index'))

@home_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home_bp.index'))

def get_user_info(steam_id):
    """
    Return player summaries of the user that has the steam_id.

    Example:
    {
        u'steamid': u'steamid',
        u'personaname': u'personaname',
        ...
    }

    See: https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29
    """

    api = 'http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?'
    params = {
        'key': current_app.config['STEAM_API_KEY'],
        'steamids': steam_id,
        'format': json
    }
    user_info = requests.get(url=api, params=params)
    user_info_json = user_info.json()

    return user_info_json['response']['players'][0] or {}

scrim2/views/profile.py
from flask import Blueprint, render_template, url_for, g, redirect
from flask.ext.login import login_required
from sqlalchemy.orm.exc import NoResultFound, MultipleResultsFound
from scrim2.models import User
from scrim2.extensions import db, rds
from scrim2.forms import EditUserForm

profile_bp = Blueprint('profile_bp', __name__)

@profile_bp.route('/profile')
@login_required
def my_profile():
    return redirect(url_for('profile_bp.profile', steam_id=g.user.steam_id))

@profile_bp.route('/profile/<steam_id>')
@login_required
def profile(steam_id):
    try:
        u = User.query.filter_by(steam_id=steam_id).one()
        status = rds.get(u.id)
        return render_template('/profile/profile.html',
                u=u,
                status=status)
    except NoResultFound:
        return "no", 404

@profile_bp.route('/profile/edit', methods=['GET', 'POST'])
@login_required
def profile_edit():

    form = EditUserForm()

    if form.validate_on_submit():
        g.user.skill_level = form.skill_level.data
        g.user.main_class = form.main_class.data
        db.session.add(g.user)
        db.session.commit()
        # flash()
        return redirect(url_for('profile_bp.my_profile'))
    else:
        form.main_class.data = g.user.main_class
        form.skill_level.data = g.user.skill_level
        return render_template('/profile/profile_edit.html', form=form)

scrim2/views/teams.py
from flask import Blueprint, render_template, g, redirect, url_for
from flask.ext.login import login_required
from scrim2.extensions import db

teams_bp = Blueprint('teams_bp', __name__)

@teams_bp.route('/team/<id>')
@login_required
def team(id):
    return render_template('/teams/team.html')

@teams_bp.route('/teams', methods=['GET', 'POST'])
@teams_bp.route('/teams/page/<int:page>', methods=['GET', 'POST'])
@login_required
def teams(page=1):
    return render_template('teams/teams.html')

@teams_bp.route('/team/new', methods=['GET', 'POST'])
@login_required
def team_new():
    return render_template('/teams/team_new.html')

@teams_bp.route('/team/edit/<team_id>', methods=['GET', 'POST'])
@login_required
def team_edit(team_id):
    return render_template('/teams/team_edit.html')

@teams_bp.route('/team/delete/<team_id>')
@login_required
def team_delete(team_id):
    return 'OK'

"""
promote, demote, kick
"""

scrim2/templates/home/index.html
{% extends "home/layout_index.html" %}
{% block body %}
<div class="container">
      

      <div class="jumbotron" style="border-radius: 1%">
        <h1>scrim.me V2</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="{{url_for('home_bp.login')}}" role="button"><i class="fa fa-steam"></i> Login With Steam</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4><i class="fa fa-bolt"></i> Live Scrims</h4>
          <p>A dedicated Live Scrims page where you can post and find scrims in real time. No more IRC!</p>

          <h4><i class="fa fa-male"></i> Live Merc Listings</h4>
          <p>Don't have a team but still want to practice? Are you looking for an extra player. List yourself as a merc or find a merc on the Live Scrims page!</p>

          <h4><i class="fa fa-comment"></i> Live Chat</h4>
          <p>Live Scrims are organized using live chat between leaders.</p>
        </div>

        <div class="col-lg-6">
          <h4><i class="fa fa-cogs"></i> Team Management</h4>
          <p>Organize your team, mark availability times on the integrated spreadsheets, add and kick players, promote leader.</p>

          <h4><i class="fa fa-envelope-o"></i> Player Messages</h4>
          <p>Integrated messaging between players. Is the team leader offline? Message him directly.</p>

          <h4><i class="fa fa-volume-up"></i>  Audio Notification</h4>
          <p>You will be alerted when you receive a scrim challenge or new message.</p>
        </div>
      </div>

      <footer class="footer">
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

{% endblock %}

scrim2/templates/home/layout.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<link type="text/css" rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}"  media="screen,projection"/>
<link type="text/css" rel="stylesheet" href="{{url_for('static', filename='css/custom.css')}}"  media="screen,projection"/>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
{% block nav %}
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">scrim.me V2</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{url_for('live_bp.live')}}"><i class="fa fa-bolt"></i> Live <span class="sr-only">(current)</span></a></li>
        <li><a href="{{url_for('teams_bp.teams')}}"><i class="fa fa-users"></i> Teams</a></li>
        <li><a href=""><i class="fa fa-user"></i> Players</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-steam-square"></i><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{url_for('profile_bp.my_profile')}}"><i class="fa fa-eye"></i> Profile</a></li>
            <li><a href="{{url_for('profile_bp.profile_edit')}}"><i class="fa fa-pencil-square-o"></i> Edit</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{{url_for('home_bp.logout')}}"><i class="fa fa-sign-out"></i> Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>        
{% endblock %}
{% block body %}

{% endblock %}

{% block after_body %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script src="https://cdn.socket.io/socket.io-1.3.5.js"></script>
{% endblock %}

{% block footer %}
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>
{% endblock %}
</body>
</html>

scrim2/templates/home/layout_index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<link type="text/css" rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}"  media="screen,projection"/>
<link type="text/css" rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}"  media="screen,projection"/>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
{% block body %}

{% endblock %}



{% block after_body %}
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
{% endblock %}

</body>
</html>